name: the_hero_brain
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^1.2.6
  introduction_screen: ^1.0.9
  shared_preferences: ^0.5.8
  after_layout: ^1.0.7+2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/gifs/
    - assets/images/nature/cloud/
    - assets/images/nature/desert/
    - assets/images/nature/earth/
    - assets/images/nature/lightning/
    - assets/images/nature/moon/
    - assets/images/nature/mountain/
    - assets/images/nature/rain/
    - assets/images/nature/rainbow/
    - assets/images/nature/river/
    - assets/images/nature/sea/
    - assets/images/nature/snow/
    - assets/images/nature/star/
    - assets/images/nature/stone/
    - assets/images/nature/sun/
    - assets/images/nature/waterfall/
    - assets/images/animal/bear/
    - assets/images/animal/bird/
    - assets/images/animal/cat/
    - assets/images/animal/chicken/
    - assets/images/animal/cow/
    - assets/images/animal/dog/
    - assets/images/animal/elephant/
    - assets/images/animal/giraffe/
    - assets/images/animal/horse/
    - assets/images/animal/ladybug/
    - assets/images/animal/lion/
    - assets/images/animal/panda/
    - assets/images/animal/penguin/
    - assets/images/animal/sheep/
    - assets/images/animal/turtle/
    - assets/images/plant/apple/
    - assets/images/plant/banana/
    - assets/images/plant/beans/
    - assets/images/plant/carrot/
    - assets/images/plant/cucumber/
    - assets/images/plant/eggplant/
    - assets/images/plant/flower/
    - assets/images/plant/grape/
    - assets/images/plant/melon/
    - assets/images/plant/mushrooms/
    - assets/images/plant/pepper/
    - assets/images/plant/pumpkin/
    - assets/images/plant/strawberry/
    - assets/images/plant/tomato/
    - assets/images/plant/tree/
    - assets/images/plant/watermelon/
    - assets/images/thing/bed/
    - assets/images/thing/book/
    - assets/images/thing/chair/
    - assets/images/thing/door/
    - assets/images/thing/dress/
    - assets/images/thing/fork/
    - assets/images/thing/glass/
    - assets/images/thing/house/
    - assets/images/thing/lamp/
    - assets/images/thing/plate/
    - assets/images/thing/scissors/
    - assets/images/thing/shoe/
    - assets/images/thing/spoon/
    - assets/images/thing/tap/
    - assets/images/thing/window/

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
